name = "IterativePerturbationTheory"
uuid = "bd90abd5-66b6-409b-9c8a-d9ba282b4dcc"
authors = ["Matteo Smerlak <matteo.smerlak@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
LinearMapsAA = "599c1a8e-b958-11e9-0d14-b1e6b2ecea07"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
MKLSparse = "0c723cd3-b8cd-5d40-b370-ba682dde9aae"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
Traceur = "37b6cedf-1f77-55f8-9503-c64b63398394"
